## OMSA

#discovery
UserParameter=omsa.pddiscovery,sudo /home/zabbix/.sh/omsa.sh pddiscovery
UserParameter=omsa.vddiscovery,sudo /home/zabbix/.sh/omsa.sh vddiscovery
UserParameter=omsa.fandiscovery,sudo /home/zabbix/.sh/omsa.sh fandiscovery
UserParameter=omsa.psudiscovery,sudo /home/zabbix/.sh/omsa.sh psudiscovery
UserParameter=omsa.ramdiscovery,sudo /home/zabbix/.sh/omsa.sh ramdiscovery
UserParameter=omsa.tempdiscovery,sudo /home/zabbix/.sh/omsa.sh tempdiscovery

#checks
UserParameter=omsa.pdstatus[*],sudo /home/zabbix/.sh/omsa.sh pdstatus $1 $2 $3
UserParameter=omsa.vdstatus[*],sudo /home/zabbix/.sh/omsa.sh vdstatus $1 $2 $3
UserParameter=omsa.fanstatus[*],sudo /home/zabbix/.sh/omsa.sh fanstatus $1 $2
UserParameter=omsa.psustatus[*],sudo /home/zabbix/.sh/omsa.sh psustatus $1
UserParameter=omsa.ramstatus[*],sudo /home/zabbix/.sh/omsa.sh ramstatus $1
UserParameter=omsa.tempstatus[*],sudo /home/zabbix/.sh/omsa.sh tempstatus $1
UserParameter=omsa.model,sudo /home/zabbix/.sh/omsa.sh model
UserParameter=omsa.stag,sudo /home/zabbix/.sh/omsa.sh stag
UserParameter=omsa.bios,sudo /home/zabbix/.sh/omsa.sh bios
UserParameter=omsa.idrac,sudo /home/zabbix/.sh/omsa.sh idrac
UserParameter=omsa.status,sudo /home/zabbix/.sh/omsa.sh status

# power monitoring
UserParameter=omsa.pwrdiscovery,sudo /home/zabbix/.sh/omsa.sh pwrdiscovery
UserParameter=omsa.pwrstatus[*],sudo /home/zabbix/.sh/omsa.sh pwrstatus $1

# bmc
UserParameter=omsa.bmc[*],sudo /home/zabbix/.sh/omsa.sh bmc $1

# batteries (CMOSバッテリー含む)
UserParameter=omsa.battdiscovery,sudo /home/zabbix/.sh/omsa.sh battdiscovery
UserParameter=omsa.battstatus[*],sudo /home/zabbix/.sh/omsa.sh battstatus $1 $2
